using UnityEngine;

namespace GLTFast.Materials
{
    /// <summary>
    /// ShaderGraph material generated by UniversalRPMaterialGenerator performs bad.
    /// Especially when there are transparent objects and pixel overdraw happens.
    /// Lit shader material in UniversalRPLitShaderMaterialGenerator is implemented based on URP v12.1.7 lit shader and unlit shader.
    /// So it could not be compatible with lower URP versions.
    /// </summary>
    [CreateAssetMenu(fileName = "glTFastUniversalRPMaterialConfig", menuName = "glTFast/UniversalRPMaterialConfig", order = 1)]
    public class UniversalRPMaterialConfig : ScriptableObject
    {
        [Header("Disabling this will improve performance on pixel shader. Recommend to disable this only on URP version 12.1.7 or later")]
        public bool useShaderGraphMaterial = true;
    }
}
